version: "3"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.15
    container_name: esprobation01
    environment:
      - node.name=esprobation01
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - ${ELASTICSEARCH_PORT}:9200
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.15
    container_name: kibprobation01
    environment:
      - ELASTICSEARCH_HOSTS=http://esprobation01:9200
    ports:
      - ${KIBANA_PORT}:5601
    depends_on:
      - elasticsearch
    networks:
      - elastic

  postgres:
    image: postgres
    container_name: probation01_postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    networks:
      - elastic
    volumes:
      - postgresql_data:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus
    container_name: probation01_prometheus
    ports:
      - "${PROMETHESUS_PORT}:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - elastic

  grafana:
    image: grafana/grafana
    container_name: probation01_grafana
    ports:
      - "${GRAFANA_PORT}:3000"
    networks:
      - elastic

networks:
  elastic:
    driver: bridge

volumes:
  postgresql_data:
    driver: local