version: "3.9"
services:
  postgres:
    container_name: postgres-project-prob
    image: postgres:latest
    ports:
    - "5432:5432"
    volumes:
    - /data/postgres:/data/postgres
    env_file:
    - docker.env
    networks:
    - postgres
  mongodb:
    container_name: mongodb
    image: mongo:6.0
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - /data/mongodb_data:/data/mongodb_data
    environment:
    - docker.env   
networks:
  postgres:
    driver: bridge
  # nest-backend:
  #   container_name: boilerplate
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "7xxx:7xxx"
  #   restart: unless-stopped
  #   environment:
  #     VITE_CRYPTO_SECRET_KEY: "xxxxx"  
  #     VITE_CRYPTO_IV_KEY: "xxxxx"
  #     TOKEN_EXP: "12h"                              
  #     TOKEN_SECRET: "xxxxx"                
  #     DB_HOST: "xxxxx"
  #     DB_PORT: "xxxxx"
  #     DB_USERNAME: "xxxxx"
  #     DB_NAME: "xxxxx"
  #     DB_PASSWORD: "xxxxx"
  #     APP_PORT: "xxxxx"
  #     MONGODB_URL: "xxxxx"
  #     MONGODB_DBNAME: "xxxxx"
